### PR TITLE
Feature/pipeline draft

### PR DESCRIPTION
**Pull request by mishraomp**
Initial Pull request which needs to be merged for the actions to show up on action tab.
The actions would not be triggered to other than tools env which should not impact the dev team.
Currently the focus is running against tools env and get going, once successful, other workflows files would be updated accordingly.

Pipeline changes for build and deployment,

# How Has This Been Tested?

Testing could only be done after merging to dev branch and actions showing up in actions tab,

### CODE REVIEW

**Review by sakthi-aot — APPROVED** [review]
Looks good

**Review by acoard-aot — APPROVED** [review]
Looking through this it looks really good, happy to merge it in and see if it works/what needs tweaking.

I am a bit unclear on the purpose of the `ci-cd-openshift-tools.yaml` file is for and why we are using the tools environment at all.  Are you just using it as an iteration cycle and making sure it works there before touching dev? Either way, looks good.  

I will merge this in and monitor if any GitHub Actions trigger etc.

**Comment by acoard-aot** [comment]
Looks like progress but still failing on deploy step.

Backend: https://github.com/bcgov/nr-epd-digital-services/actions/runs/3362983073/jobs/5575571211

Frontend: https://github.com/bcgov/nr-epd-digital-services/actions/runs/3362983073/jobs/5575571211

Also, for info, I ran below command, as I don't think the pipeline dev service account had access to tools (I just set it up to dev/test/prod previously).  However, not sure that's the issue, as error logs are about lcov or yaml parsing.

`oc policy add-role-to-user edit system:serviceaccount:****-dev:pipeline -n e38158-tools` (namespace redacted)

**Comment by mishraomp** [comment]
yeah, I am on it, needs tweaking to build, since it is not finding any diff, it is not building anything

**Comment by mishraomp** [comment]
I have added tools env and appropriate token and namespace as secrets in settings.

**Comment by acoard-aot** [comment]
Perfect, thanks Om.  Yeah it makes total sense to use tools env like this, just took me a sec to wrap my head around it.

**Pull request merged**
